### ISSUE TITLE
Little incompatibility for pip 10.0.1 in setup.py

### ISSUE THREAD

**Issue by strayMat** [jtourille/yaset#3]
When launching `pip install . ` with pip 10.0.1, I had the following error : 
`module 'pip' has no attribute 'get_installed_distributions'`

I fixed it with the following [post](https://github.com/phildini/thanks/issues/19). 
It is sufficient to add `from pip._internal.utils.misc import get_installed_distributions` in the setup.py and change `pip.get_installed_distributions` to  `get_installed_distributions`. 
 
I am not sure if this is very important or if it is easy to make a fix that could work with both pip 10.0.1 and pip <=9.* but it is always good to know.
